<div class="widget-accordion">
    
    <a href="#" data-dropdown="drop" class="[tiny small medium large] [secondary alert success] [radius round] button dropdown">Config</a><br>
    <ul id="drop" data-dropdown-content class="f-dropdown">
      <li><a href="#" class="edit" data-reveal-id="configModal">Edit</a></li>
      <li><a href="#">Delete</a></li>
    </ul>
    
    <dl class="accordion" data-accordion>
        <dd class="accordion-navigation">
            <a href="#panel1b">Accordion 1</a>
            <div id="panel1b" class="content active">Panel 1. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
        </dd>
        <dd class="accordion-navigation">
            <a href="#panel2b">Accordion 2</a>
            <div id="panel2b" class="content">Panel 2. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
        </dd>
        <dd class="accordion-navigation">
            <a href="#panel3b">Accordion 3</a>
            <div id="panel3b" class="content">Panel 3. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
        </dd>
    </dl>
</div>